/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6f1478805ff9f409db0d6cdf74cd8e59)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
	}
	interface Env {
		HYPERDRIVE: Hyperdrive;
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		VITE_SB_ID: string;
		VITE_SB_URL: string;
		VITE_SB_PUBLISHABLE_KEY: string;
		SB_SECRET_KEY: string;
		VITE_CLERK_PUBLISHABLE_KEY: string;
		CLERK_SECRET_KEY: string;
		CLERK_SIGN_IN_URL: string;
		CLERK_SIGN_IN_FALLBACK_REDIRECT_URL: string;
		CLERK_SIGN_UP_FALLBACK_REDIRECT_URL: string;
		R2_ENDPOINT: string;
		R2_ACCESS_KEY: string;
		R2_BUCKET: string;
		R2_SECRET_ACCESS_KEY: string;
		R2_PUBLIC_BASE_URL: string;
		R2_TOKEN: string;
		UMAMI_API_KEY: string;
		UMAMI_API_CLIENT_ENDPOINT: string;
		UMAMI_WEBSITE_ID: string;
		VITE_UMAMI_WEBSITE_ID: string;
		VITE_UMAMI_SCRIPT_URL: string;
		VITE_MAPBOX_ACCESS_TOKEN: string;
		VITE_MAPBOX_PUBLIC_TOKEN: string;
		VITE_CRAWLER_SERVER_ENDPOINT: string;
		RESEND_API_KEY: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		DATABASE_URL: string;
		DIRECT_URL: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VALUE_FROM_CLOUDFLARE" | "VITE_SB_ID" | "VITE_SB_URL" | "VITE_SB_PUBLISHABLE_KEY" | "SB_SECRET_KEY" | "VITE_CLERK_PUBLISHABLE_KEY" | "CLERK_SECRET_KEY" | "CLERK_SIGN_IN_URL" | "CLERK_SIGN_IN_FALLBACK_REDIRECT_URL" | "CLERK_SIGN_UP_FALLBACK_REDIRECT_URL" | "R2_ENDPOINT" | "R2_ACCESS_KEY" | "R2_BUCKET" | "R2_SECRET_ACCESS_KEY" | "R2_PUBLIC_BASE_URL" | "R2_TOKEN" | "UMAMI_API_KEY" | "UMAMI_API_CLIENT_ENDPOINT" | "UMAMI_WEBSITE_ID" | "VITE_UMAMI_WEBSITE_ID" | "VITE_UMAMI_SCRIPT_URL" | "VITE_MAPBOX_ACCESS_TOKEN" | "VITE_MAPBOX_PUBLIC_TOKEN" | "VITE_CRAWLER_SERVER_ENDPOINT" | "RESEND_API_KEY" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "DATABASE_URL" | "DIRECT_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET">> {}
}
